// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEu_HduvmtLl0V3DQgmFEivUORECcodfI',
    appId: '1:468721989017:web:18dd9621619938c30b0f08',
    messagingSenderId: '468721989017',
    projectId: 'nimbus-ad94f',
    authDomain: 'nimbus-ad94f.firebaseapp.com',
    storageBucket: 'nimbus-ad94f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBqyNUv5IEcSIEP_GK70bd46bAx6a7FyY',
    appId: '1:745026219313:android:bc0fb8e6dab98cac9a5410',
    messagingSenderId: '745026219313',
    projectId: 'nimbuus',
    storageBucket: 'nimbuus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD27sID-Rb4IxHuirv--3uq5M1H0byTmcI',
    appId: '1:468721989017:ios:c6b35fa752622f290b0f08',
    messagingSenderId: '468721989017',
    projectId: 'nimbus-ad94f',
    storageBucket: 'nimbus-ad94f.firebasestorage.app',
    iosBundleId: 'com.nimbus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD27sID-Rb4IxHuirv--3uq5M1H0byTmcI',
    appId: '1:468721989017:ios:cf4008220fb751610b0f08',
    messagingSenderId: '468721989017',
    projectId: 'nimbus-ad94f',
    storageBucket: 'nimbus-ad94f.firebasestorage.app',
    iosBundleId: 'com.example.nimbus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEu_HduvmtLl0V3DQgmFEivUORECcodfI',
    appId: '1:468721989017:web:3f5e627d93f820f20b0f08',
    messagingSenderId: '468721989017',
    projectId: 'nimbus-ad94f',
    authDomain: 'nimbus-ad94f.firebaseapp.com',
    storageBucket: 'nimbus-ad94f.firebasestorage.app',
  );

}